### ISSUE TITLE
Handle enhanced weapons better

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#10516]
enhanced weapon improvements checklist:

- [x] distinguish them from crafted
- [x] stop matching is:crafted #10552
- [x] #10674
- [x] change their item popup tooltip icon
- [x] #10715
- [x] #10719
- [x] add gold border when T3 enhanced #10522
- [x] enhanceable perks are showing up as not droppable (red)? #10553
- [x] #10550

**Comment by JxPv2** [comment]
In the wishlist enhanced perks for non crafted weapons are not showing at all
![image](https://github.com/DestinyItemManager/DIM/assets/85701176/1c3e443c-2432-4a4e-87de-080e520f3300)
![image](https://github.com/DestinyItemManager/DIM/assets/85701176/005571ea-7d13-42b7-8b6b-97e9bae69dde)

**Comment by bhollis** [comment]
Thanks @FlaminSarge for finishing the last of these tasks!
