### ISSUE TITLE
[i18n] Missing Translations

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1133]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85

A large i18n update has been pushed, please add any translations that are missing for your language.

EDIT: Be sure to also check /app/views/(language) to translate the about and support pages.
- [x] German Translations @crulplay @Korben85 
- [x] French Translations #1163 @yannickguillemot 
- [x] Portuguese Translations #1164 @brunnopleffken 
- [x] Spanish Translations #1168 #1170 #1171 @JaviG1105 
- [x] Italian translations - #1195 #1196 #1197 #1200 #1203 @simonefranza

Translators still needed for:

- [ ] Japanese Translations - Response rec'd

Reddit posts:
https://www.reddit.com/r/DestinyTheGame/comments/5cgphg/dim_is_looking_for_translation_help/
https://www.reddit.com/r/DestinyItemManager/comments/5b5g8f/translation_help/

**Comment by yannickguillemot** [comment]
I am working on a local branch for the french translation.

**Comment by brunnopleffken** [comment]
So do I for Portuguese translation.

**Comment by delphiactual** [comment]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85, @JaviG1105:

Are any of you in the ThisIsDIM slack channel? If so, please post your username here, if not please join https://thisisdimslack.stamplayapp.com/ and post your username here. @SunburnedGoose created us a i18n channel that should definitely help with translations, if the main copy is changed.

**Comment by delphiactual** [comment]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85, @JaviG1105, @simonefranza:

The following i18n tasks are currently non-complete:
 - French
   - [ ] `support.html`
   - [ ] `best-help.html`
 - Portuguese
   - [ ] `best-help.html`
 - All
   - Please check the i18n file for any new missing keys for your language.

**Comment by delphiactual** [comment]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85, @JaviG1105, @simonefranza:

New keys added in #1237 & #1239

**Comment by delphiactual** [comment]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85, @JaviG1105, @simonefranza:

I have added gender support for i18n, I just need to know which keys need gender support added as the format for these keys will be slightly different.

**Comment by delphiactual** [comment]
@brunnopleffken, @yannickguillemot, @crulplay, @Korben85, @JaviG1105, @simonefranza:

All further i18n discussion/translations will take place here:
https://www.transifex.com/destiny-item-manager/destiny-item-manager/
