### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#194]
The app needs to adjust to the available width of the viewport and still maintain the functionality of:

* Refesh Data
* Menu Items
  * Settings
  * About
  * Support DIM
* Platform switching
* Access to loadouts
  * CRUD operations
  * Applying a loadout to a character
  * Ability to search for and select a loadout.
* Access to characters and the vault
* Quickly scan equipped and stored items on characters and vault
* Easily scan similar items across characters and the vault
* Item detail screen for perks and stats
* Quickly move items between characters and vault
  * Drag and drop items between characters
  * Popup dialog with move/equip targets

### Task List
- [ ] #195 Responsive Layout Scaffolding
- [ ] #196 Responsive Item Store Selection
- [ ] #197 Responsive Move Item Dialog

**Comment by jflayhart** [comment]
For my own task list...

1. Make Top Nav Bar responsive. Username will act as a drop down when under 480px wide with menu items and settings.
2. #197
