### ISSUE TITLE
checklist for additional power limit & icon work

### ISSUE THREAD

**Issue by archived-2f4dd0** [DestinyItemManager/DIM#5283]
- [x] it's still just added to item stats, for the sake of making compare tool work. should we leave this? should we hide the stat in item popup?

- [x] clean up stat work if we are keeping it, extract numbers to constants

- [x] test colors on opaque corners of overlaid elements

- [ ] look for ways to compose these image stacks with fewer elements

- [ ] remove string checking regex on level filter, make use of it on sunset filter by allowing season names instead of numbers

- [ ] seriously maybe better filter names

**Comment by DHager** [comment]
> should we hide the stat in item popup?

Personally, in the short term I'm very interested in the infusion-cap/power-limit for items, since the lowest are 1060 and therefore their end-of-life (at least for PvE and Iron Banner) is on the horizon, with the associated desire to prune my vault a bit.

I think I'd largely want to work in terms of the actual power-limit numbers themselves, rather than season-names (which are harder to mentally order) or season numbers (since everyone says "Arrival" rather than "11".)

**Comment by DHager** [comment]
P.S.: Also at the risk of pointing out the obvious, the current `season:=N` filter doesn't tell you anything useful about sunsetting-status. For example, my "season 1" Sovereign Grips that have a 1310 infuse-cap, whereas "season 2" Annealed Shaper Gloves are capped at 1060.

**Comment by sundevour** [comment]
i think @delphiactual would agree that even season has existed as a strict source of "when did it show up in-game" up til now, and `modslot`, `holdsmod`, and `sunsetsafter` are the right filters to use for various seasonally related game mechanics

**Comment by DHager** [comment]
Right, I just wanted to emphasize that--at least for me--the power numbers are the most important thing, because I don't really think in terms of season-names or season-numbers.

**Comment by sundevour** [comment]
that should be covered by `powerlimit:`

**Comment by DHager** [comment]
I'd like to use the power-limits in spreadsheet exports too. Is that part of this task, or should I create a separate PR?

**Comment by sundevour** [comment]
there's a column in organizer but i am not sure how fully hooked to to spreadsheet exports that is. please drop me an issue and @ me in it and i will make sure it's in exports this weekend
