### ISSUE TITLE
Active Mode follow ups

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5976]
- [x] ~Drag/drop an item to character tile~ (cancelled because of #6216)
- [x] ~Suggested bounties should be based on your activity type across all vendors, and not the vendors activity or location type. (Banshee/Recaster pvp bounties should show for pvp/pve depending on activity)~ (moved to #6218) 
- [x] Inventory category items when you select the non-active character makes them all show up in the 'rest bucket' (#6136)
- [x] Suggested ghost should pull from all stores, not just selected store. (#6036)
- [x] Filter `Recent Items` via search (#6026)
- [X] Style `No tracked triumphs` (#5986)
- [x] maxpower search is only applied to recent items
- [X] Dedupe non-transferabble (#5993)
- [x] Track Items (#6026)

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/95662944-03643c80-0af8-11eb-949c-772c97326a16.png)

Flashpoint shows up twice

**Comment by delphiactual** [comment]
![image](https://user-images.githubusercontent.com/4798491/95667277-1a6b5480-0b21-11eb-9742-84a6c425376f.png)

**Comment by delphiactual** [comment]
`is:maxpower` seems to return weird results

**Comment by delphiactual** [comment]
Dedupe `Finishers`, `Seasonal Artifact`, `Clan Banners`

**Comment by delphiactual** [comment]
add ability to track items e.g. chocolate coins, candy, decoders

**Comment by delphiactual** [comment]
@kyleshay i do not think #6026 addresses wrong search results for maxpower

**Comment by kyleshay** [comment]
ah hmm i'll double check, i think i know what the problem is (it's related to recent items... maxpower is showing maxpower in your recent items, haha)

**Comment by delphiactual** [comment]
that is what it appears to be doing.

**Comment by delphiactual** [comment]
Vault Portion of `Mods` is showing `Recent Items`

**Comment by kyleshay** [comment]
down to just one, splitting it to a new request to track separately #6218
