### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#737]
Let's do a release soon! The changelog is looking juicy!

What do we want fixed before the release? I can think of:

* ~~#723 - Record books in vault~~ (not release blocking, should fix before RoI release)
* [x] #721 - Can't develop locally (is that release blocking?)
* [x] #741 - Visual tweaks to Vendors
* [x] #708 - To help out Bungie folks
* [x] #757 - Fix platform switching
* [x] #750 - Mark created loadout as equipped (possibly resolved in #777)
* [x] #761 - Add a setting for new items

**Comment by ericnelson0** [comment]
I'm making some progress on #709. Should be soon.

**Comment by bhollis** [comment]
Awesome, almost there. If we can make a decision on #761 and a quick fix for #750, I say go!

**Comment by bhollis** [comment]
All issues resolved! GOGOGO

![bitmoji](https://render.bitstrips.com/v2/cpanel/9090400-136424313_5-s4-v1.png?transparent=1&width=246)
